In [1]:
import csv

%precision 2

with open('datasets/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
#mpg

In [2]:
sum(float(d['displ']) for d in mpg)

812.40

http://pythonstudy.xyz/python/article/23-Iterator%EC%99%80-Generator

In [3]:
k = iter(float(d['displ']) for d in mpg)
sum(k)

812.40

In [4]:
import datetime as dt
import time

time = time.time()
dtnow = dt.datetime.fromtimestamp(time)
dtnow.year

2021

In [5]:
delta = dt.timedelta(days=300)
dtnow - delta

datetime.datetime(2020, 11, 9, 10, 42, 11, 76660)

1. Python doesn't have private or protected, all instances and methods are public
2. map built-in func is one example of a functional programming feature

# Map Function
1. Functional programming is a programming paradigm in which you explicitly declare all parameters which could change through execution of a given function. Thus functional programming is referred to as being side-effect free, because there is a software contract that describes what can actually change by calling a function. Now, Python isn't a functional programming language in the pure sense. Since you can have many side effects of functions, and certainly you don't have to pass in the parameters of everything that you're interested in changing. But functional programming causes one to think more heavily while chaining operations together. And this really is a sort of underlying theme in much of data science and date cleaning in particular.
 
2. Check Python documentation about map
3. Python의 map object는 lazy evaluation -> user가 result나 contents 보기 전까지는 계산 안함 -> efficient memory management
4. This passing around of functions and data structures which they should be applied to, is a hallmark of functional programming. It's very common in data analysis and cleaning

In [6]:
#Quiz about map() function
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    lst = person.split(' ')
    return lst[0] + ' ' + lst[-1]

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

# lambda
0. anonymous func
1. Default value나 Complex Logic은 사용 불가능
2. Useful for simple little data cleaning task

In [7]:
def add(a,b):
    return a+b

func = lambda a, b, c : add(a,b)
func(5,55,2)

60

# List Comprehension
[(Value you want) (For loop) (Condition)]

1. It offer readability and performance benefit(?)
<Q> 왜 performance benefit이 있지

In [8]:
[number for number in range(1000) if number > 300 and number%2==1]
(number for number in range(1000) if number > 300 and number%2==1)

<generator object <genexpr> at 0x7f0f70719a98>

In [2]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

#times_tables()

In [10]:
import itertools

quiz = [num1*num2 for num1,num2 in list(itertools.product(range(10),range(10)))]
times_tables() == quiz

True

# Numpy



In [4]:
import numpy as np
import math


arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [9]:
txt = 'I refer to https://google.com and i never refer http://www.baidu.com'
print(txt.findall(?<=https:\/\/)([A-Za-z0-9.]*))

SyntaxError: invalid syntax (<ipython-input-9-3a0212db9552>, line 2)

In [12]:
np.random.rand(3,4)
np.arange(10,51,3) #Create array with difference k from start to end
np.linspace(0,2,15) #Create array with k elements from start to end that has same difference


array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [13]:
a = np.arange(10,50,10)
b = np.arange(1,5,1)
a-b
a+b
a*b
a/b
a**b
a@b #Product 내적

300

In [14]:
#If I write code with Array c(not specific element like c[2][3]), code is applied to all variables
#This is elementwise operation
c = np.random.randint(0,30,(5,6))
d = c*9/5+32

In [15]:
#I can also use Conditional operator
d > 40
d%2==1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False]])

In [16]:
#When manipulating arrays of different types, the type of the result will correspond to
#the more general of the two types -> upcasting
e = np.linspace(0,2,5)
f = np.random.randint(0,5,5)
(e+f).dtype

dtype('float64')

In [17]:
g = e+f
g.min()
g.sum()
g.mean()

2.0

In [18]:
np.zeros((5,6))
np.ones((6,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [19]:
h = np.arange(1,16,1).reshape(3,5)
lst = [3,4,5,6,7]
h, sum(lst)

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]), 25)

In [20]:
#map function is appled for each row
list(map(lambda x:x.sum(),h))

[15, 40, 65]

Now, we often think about two dimensional arrays being made up of rows and columns, but you can also think of these arrays as just a **giant ordered list of numbers**, and the *shape* of the array, the number of rows and columns, is just an abstraction that we have for a particular purpose. 
Actually, **this is exactly how basic images are stored in computer environments.**

In [3]:
from PIL import Image
from IPython.display import display

# And let's just look at the image I'm talking about
im = Image.open('chris.tiff')
im2 = Image.open('god.jpg')
#display(im),display(im2)

In [4]:
arr1 = np.array(im)
arr2 = np.array(im2)
arr3 = arr2 & 0x11001011
mask1 = np.full(arr1.shape,255)
mask2 = np.full(arr2.shape,255)

modified1 = mask1 - arr1
modified2 = mask2 - arr2

#modified1, modified2

NameError: name 'np' is not defined

In [5]:
modified1.dtype, modified2.dtype
modified1= modified1.astype(np.uint8)
modified2 = modified2.astype(np.uint8)
arr3 = arr3.astype(np.uint8)

modified1.dtype, modified2.dtype
#modified1,modified2

NameError: name 'modified1' is not defined

In [24]:
#display(Image.fromarray(arr3))
#display(Image.fromarray(modified2))

In [25]:
reshaped1 = np.reshape(arr1,(100,400))
reshaped2 = np.reshape(arr2,(250,1458,3))
arr2.shape, reshaped2.shape

((675, 540, 3), (250, 1458, 3))

In [26]:
#display(Image.fromarray(reshaped1))
#display(Image.fromarray(reshaped2))

 Can't say I find that particularly flattering. By reshaping the array to be only 100 rows high but 400
 columns we've essentially doubled the image by taking every other line and stacking them out in width. This
 makes the image look more stretched out too.

 This isn't an image manipulation course, but the point was to show you that these numpy arrays are really
 **just abstractions on top of data, and that data has an underlying format (in this case, uint8).** But further,
 we can build abstractions on top of that, such as computer code which renders a byte as either black or 
 white, which has meaning to people. In some ways, this whole degree is about data and the abstractions that
 we can build on top of that data, from individual byte representations through to complex neural networks of
 functions or interactive visualizations. **Your role as a data scientist is to understand what the data means
 (it's context an collection), and transform it into a different representation to be used for sensemaking.**

In [27]:
#In i[n:k], i[k] is not contained in result
i = np.random.randint(10,40,(5,6))
i,i[1:3],i[[2,3],[3,5]]

(array([[35, 11, 35, 14, 13, 31],
        [17, 25, 18, 27, 39, 34],
        [25, 31, 11, 26, 37, 31],
        [17, 35, 30, 25, 14, 16],
        [27, 35, 23, 12, 32, 27]]), array([[17, 25, 18, 27, 39, 34],
        [25, 31, 11, 26, 37, 31]]), array([26, 16]))

#We can use **array of boolean like a mask over the original array**

In [28]:
i[i > 20]

array([35, 35, 31, 25, 27, 39, 34, 25, 31, 26, 37, 31, 35, 30, 25, 27, 35,
       23, 32, 27])

In [29]:
portion =i[3:5][:5]
portion

array([[17, 35, 30, 25, 14, 16],
       [27, 35, 23, 12, 32, 27]])

It is important to realize that a slice of an array is a view into the same data. This is called **passing by reference**. So **modifying** the sub array will consequently modify the original array

However, array operation of subarray is not applied to original array

In [30]:
#<Q> Matrix의 원소들 한 번에 바꾸는 법은 없나
#<A> i[row, col] = val
i[3][4]=1111
#i[4:][:4] = 555 -> 보면 row들은 한 번에 적용이 되는데 column은 적용이 안됨
#i[4:,:2] = 666
portion,i

(array([[  17,   35,   30,   25, 1111,   16],
        [  27,   35,   23,   12,   32,   27]]),
 array([[  35,   11,   35,   14,   13,   31],
        [  17,   25,   18,   27,   39,   34],
        [  25,   31,   11,   26,   37,   31],
        [  17,   35,   30,   25, 1111,   16],
        [  27,   35,   23,   12,   32,   27]]))

In [31]:
portion = portion + 10
portion,i

(array([[  27,   45,   40,   35, 1121,   26],
        [  37,   45,   33,   22,   42,   37]]),
 array([[  35,   11,   35,   14,   13,   31],
        [  17,   25,   18,   27,   39,   34],
        [  25,   31,   11,   26,   37,   31],
        [  17,   35,   30,   25, 1111,   16],
        [  27,   35,   23,   12,   32,   27]]))

In [32]:
i[:-2]

array([[35, 11, 35, 14, 13, 31],
       [17, 25, 18, 27, 39, 34],
       [25, 31, 11, 26, 37, 31]])

In [33]:
wines = np.genfromtxt('datasets/winequality-red.csv',delimiter=";",skip_header=1)
wines.shape

(1599, 12)

In [34]:
wines[:5,0].shape,wines[:5,0:1].shape
wines[[4,5,6],[2,4,9]]

array([0.   , 0.075, 0.46 ])

In [6]:
graduate_admission = np.genfromtxt('datasets/Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1,
                                   names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))
#graduate_admission

NameError: name 'np' is not defined

Admission_Predict.csv가 tuple로 읽히는 이유

[Link Stack Overflow](https://stackoverflow.com/questions/9534408/numpy-genfromtxt-produces-array-of-what-looks-like-tuples-not-a-2d-array-why)

What is returned is called a structured ndarray, see e.g. here: http://docs.scipy.org/doc/numpy/user/basics.rec.html. This is because your data is not homogeneous, i.e. not all elements have the same type: the data contains both strings (the first two columns) and floats. Numpy arrays have to be homogeneous (see here for an explanation).

In [7]:
graduate_admission2 = np.genfromtxt('datasets/Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1)
#graduate_admission2 = np.genfromtxt('datasets/Admission_Predict.csv', dtype=np.float64, delimiter=',', skip_header=1)
#graduate_admission2

NameError: name 'np' is not defined

In [37]:
graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['CGPA']
#graduate_admission2[graduate_admission['Chance_of_Admit']>0.8]

array([9.65, 9.34, 9.  , 9.5 , 9.7 , 9.8 , 9.6 , 9.4 , 9.6 , 9.8 , 9.2 ,
       9.1 , 9.4 , 9.1 , 9.3 , 9.7 , 8.85, 9.64, 9.76, 9.45, 9.04, 9.5 ,
       9.22, 9.36, 9.45, 8.96, 9.24, 9.18, 9.46, 9.38, 9.56, 9.48, 9.32,
       9.1 , 9.35, 9.76, 9.28, 8.77, 9.15, 9.36, 9.44, 9.92, 8.64, 9.11,
       9.8 , 9.43, 9.28, 9.06, 9.01, 9.07, 9.13, 9.23, 8.97, 8.87, 9.16,
       9.04, 9.11, 8.68, 9.44, 9.36, 9.08, 9.16, 8.98, 8.94, 9.53, 9.91,
       9.87, 9.14, 9.66, 9.78, 9.42, 9.36, 9.26, 9.13, 8.97, 9.01, 9.31,
       9.23, 9.17, 9.19, 9.02, 9.68, 9.12, 9.34, 9.13, 9.14, 9.45, 8.79,
       9.66, 9.26, 9.19, 9.08, 9.02, 9.11, 9.24, 9.18, 9.14, 9.11, 9.47,
       8.74, 8.66, 8.44, 8.64, 9.54, 9.23, 9.17, 9.22, 9.62, 9.15, 9.74,
       9.82, 9.12, 9.23, 9.04, 9.11, 9.45, 9.66])

# Regular Expression(Regex)

[Python regex documentation](https://docs.python.org/3/library/re.html)

There's really three main reasons you would want to do this - to check whether a pattern exists within some source data, to get all instances of a complex pattern from some source data, or to clean your source data using a pattern generally through string splitting. Regexes are not trivial, but they are a foundational technique for data cleaning in data science applications, and a solid understanding of regexs will help you quickly and efficiently manipulate text data for further data science application.

Now, you could teach a whole course on regular expressions alone, especially if you wanted to demystify how the regex parsing engine works and efficient mechanisms for parsing text. In this lecture I want to give you basic understanding of how regex works - enough knowledge that, with a little directed sleuthing, you'll be able to make sense of the regex patterns you see others use, and you can build up your practical knowledge of how to use regexes to improve your data cleaning. By the end of this lecture, you will understand the basics of regular expressions, how to define patterns for matching, how to apply these patterns to strings, and how to use the results of those patterns in data processing.

In [38]:
import re

In [39]:
text = "I want to go vacance"
if re.search('vacance',text):
    print('Junyuk First')

Junyuk First


In addition to checking for conditionals, we can segment a string. The work that regex does here is called **tokenizing**, where the string is separated into substrings based on patterns. Tokenizing is a core activity in natural language processing, which we won't talk much about here but that you will study in the future


In [40]:
text = "Amy Emy Army Wowmy Shaomi Amy Limy"
re.split("Amy",text)
re.findall("Amy",text)

['Amy', 'Amy']

In [41]:
# ^ : If start with this string
text = "AAmy!!Go"
re.search("^Amy",text)
re.search("^AAmy",text)

<re.Match object; span=(0, 4), match='AAmy'>

In [42]:
# [] : set operator. In set operator other special characters like ^ loses meaning
#      ^ is used for represent "not" in set operator
# | : or

grade = "AABCDDABBBABCDBBGASDFASDFABBBSDRF@FGASDSEGDWADCAGWREAWGERQWWWQQQGEW"
len(re.findall("B",grade))
re.findall("[AB]",grade)
re.findall("D[A-C]",grade)
re.findall("DA|DB|DC",grade)
re.findall("[^A-C]",grade)
#D[A-C] = DA|DB|DC
#<Q> 어떻게 하면 모든 알파벳에 대해 back to back을 구할 수 있을까? 
re.findall("[B-Z]{2,5}",grade) #B-Z 사이의 알파벳이 반복되기만 하면 됨
re.findall("A{2,5}|B{2,5}",grade)

['AA', 'BBB', 'BB', 'BBB']

In [9]:
with open('datasets/ferpa.txt','r') as file:
    wiki = file.read()
#wiki

In [44]:
# \s : white space 
# \w : any digit and letter
# \d : any digit
re.findall('[\sa-zA-Z]{1,1000}\[edit\]',wiki)
re.findall('[\s\w]{1,1000}\[edit\]',wiki)
re.findall('[ \w]{1,1000}\[edit\]',wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [45]:
#about group
#format : (regex1)(regex2)(regex3)
#m.group(n) n번째 그룹에 매칭된 문자열 반환
#m.group() return total result
re.findall('([\w]*)(\[edit\])',wiki)
for item in re.finditer('([\w ]*)([^view])(\[edit\])',wiki):
    print(item.group(0))

Access to public records[edit]
Student medical records[edit]


In [49]:
#Can do labeling or naming groups by get result as dictionary
#finditer -> iterator로 return
for item in re.finditer('(?P<name>[\w ]*)(?P<edit_link>\[edit\])',wiki):
    print(item.group())

Overview[edit]
Access to public records[edit]
Student medical records[edit]


In [53]:
#look-ahead : Use regex to match but don't want to captrue them use "?="
#look-behind
for item in re.finditer('(?P<title>[\w ]+)(?=[ed])',wiki):
    print(item.group('etc'))

error: nothing to repeat at position 25

In [10]:
with open("datasets/buddhist.txt","r") as file:
    wiki = file.read()
#wiki

In [74]:
#verbose mode : write multi line regex
pattern = """
(?P<title>\n[\w\s]*) 
(–\ located\ in\ )
(?P<city>\w*)
(,\ )
(?P<state>\w*)
"""
for item in re.finditer(pattern,wiki,re.VERBOSE):
    print(item.groupdict())

{'title': '\n\nDhammakaya Open University ', 'city': 'Azusa', 'state': 'California'}
{'title': '\nDharmakirti College ', 'city': 'Tucson', 'state': 'Arizona'}
{'title': '\nDharma Realm Buddhist University ', 'city': 'Ukiah', 'state': 'California'}
{'title': '\nEwam Buddhist Institute ', 'city': 'Arlee', 'state': 'Montana'}
{'title': '\nInstitute of Buddhist Studies ', 'city': 'Berkeley', 'state': 'California'}
{'title': '\nMaitripa College ', 'city': 'Portland', 'state': 'Oregon'}
{'title': ' California\nUniversity of the West ', 'city': 'Rosemead', 'state': 'California'}
{'title': '\nWon Institute of Graduate Studies ', 'city': 'Glenside', 'state': 'Pennsylvania'}


In [11]:
with open("datasets/nytimeshealth.txt","r") as file:
    ny = file.read()
#ny

In [12]:
pattern = "#[\w]*(=?\s)"
#for item in re.finditer(pattern,ny):
#    print(item)

In [100]:
#특정 regex 반복하는 방법? url 문제
#?:
re.findall("[\w_^.]{2,}\.[\w_]{2,}","a..com.ddd")
re.findall("[^aeiou]","apple")

['p', 'p', 'l']

In [ ]:
Capture email address with letters, numbers, underscore and dots. A valid email address defined in this problem must meet the following requirements:
Has an "@" symbol;
Before the "@" symbol, there can be one or more strings made of letters, numbers and underscores, separated by a single dot.
After the "@" symbol, there can two or more strings made of letters, numbers and underscores, separated by a single dot.
No other characters besides letters, numbers, underscores, dots, and the "@" symbol should appear in the email address.

For example, your regular expression should match email addresses like: abc@umich.edu, 8ab.c_def9@example.regex.com;
But your regex should not match: abc@ def., ab..abc@def.com, abc@def
Your regular expression:
Drag or click to select from the symbols below to form your regex
@+*\w\.(\w+\.)(\w*\.)
Regex:
Feel free to experiment with your own test cases.
Match:
abc@umich.edu

8ab.c_def9@example.regex.com

Reset
Do not match:
abc@ def.

ab..abc@def.com

abc@def

Reset

Drag or click to select from the symbols below to form your regex
@+*\w\.(\w+\.)(\w*\.)
Regex:
(\w+\.)*\w+@(\w+\.)+\w+ #단어를 반복시키고 싶으면 grouping